### ISSUE TITLE
is it possible to change the name and description of the client side skins? 

### ISSUE THREAD

**Issue by Driagon89** [stoneharry/WoW-Spell-Editor#114]
I'm a 3.3.5 player and I wondered if it would be possible to change the name and description of the spell by translating it into Italian. 
Can you tell me if your tool can do it or if there is a way?

**Comment by stoneharry** [comment]
Italian does not look like it is a supported client language in WOTLK and prior expansion. You could translate everything English to Italian but this would be a large amount of work.

**Comment by stoneharry** [comment]
I hope the above answers your question. Translating the client into Italian would be a lot of work because it's not only the spells you need to do this for but all quests/creatures etc.

I'm going to close this question but feel free to reopen it or submit a new question if you have further queries.
