### ISSUE TITLE
How to load the spell visual map in the core?

### ISSUE THREAD

**Issue by ghost** [stoneharry/WoW-Spell-Editor#127]
So i imported all the data to the database but i had issues with the creature_template on load. I'm using azerthcore. Let me know if you need more info!

**Comment by stoneharry** [comment]
I'm going to need a ton more information to go on than this.

I cannot support every possible emulator, especially as they regularly change their database structures.

The queries this program uses are designed so that you can manually change the template query to match the emulator you are using. This is what you need to do.

Without even having the error message there is nothing more I can suggest.

**Comment by stoneharry** [comment]
Closing this as it's been open a while now, please feel free to open a new issue if you have any further questions or issues.
