### ISSUE TITLE
Spell Editor is not correctly importing changes made to DBC files from other sources

### ISSUE THREAD

**Issue by krlsmnk** [stoneharry/WoW-Spell-Editor#186]
**Spell editor version**
3.3.5A 12340

**Describe the bug**
The spell editor is not importing the DBC files correctly. Values are outright wrong. 
Both the SQL Database and the DBC File itself show the correct value. 
Spell Editor does not. 
Exporting from SpellEditor to DBC will overwrite those changes, because SpellEditor is showing default values. 

**To Reproduce**
1. I've made chances to existing blizzard spells. Specifically, mounts (all mounts). 
2: Rather than edit them one by one using the SpellEditor, I made the changes by converting the DBC to CSV. 
3: Made the changes, converted back to DBC. 
4: Placed on server and in client patch. Works as expected. 
5: Restarted everything. 
6: Opened spell editor. 
7: Changed and changed back DBC directory in SpellEditor (to try and force a correct import). 
8: I cannot manually reimport Spell.dbc. It will not let me. 
9: Open any mount spell in SpellEditor. It shows the old (default) values. 
10: Database and DBC file both show correct values. 
11: Export spell.dbc from SpellEditor. 
12: Default values now show in the DBC file.
13: Default behavior resumes on the server. 

**Expected behavior**
Spell Editor should load the values from the DBC, rather than assume them. 

**Additional context**
If you're doing some kind of diff to load the DBC files faster, you need to allow me an option to manually reimport everything from DBC, or only export the diff'd spells, rather than hard-overwriting everything that wasn't checked for changes on startup / load / import. 

New, custom spells work perfectly. Never had it scrub or forget one. Base game spells modified anywhere other than in the SpellEditor are forgotten immediately on export.

**Comment by stoneharry** [comment]
I don't think this is a bug, I think you are bypassing the spell editors workflow. Let me explain.

----

The spell editor loads the spell data from the SQL database. It is a one-time process to import the DBC data to SQL, and then from that point onwards you should always make your changes in the SQL layer. Whenever you are ready to test your changes in-game you can export the SQL data back into a new DBC.

When you edited the DBC directly the changes you made are not made in the SQL layer. The spell editor did not know about them, and it doesn't let you import the changes because you already have data imported to SQL.

What you can do is drop the data entirely, and reimport from your DBC, but this has a number of disadvantages as a process which is why the program is not designed with this as a common use case.

`Rather than edit them one by one using the SpellEditor, I made the changes by converting the DBC to CSV.`

You can do bulk edits in MySQL very easily. I would recommend doing this in future rather than converting to CSV.

----

I'm happy to discuss this further, let me know if this makes sense. If it does then we can close out this issue.

**Comment by krlsmnk** [comment]
The values in both the SQL tables and the DBC are both correct. Spell editor is showing and exporting old wrong values. I cannot make it stop doing this.

**Comment by stoneharry** [comment]
The spell editor only shows values from SQL, what it shows is what is in the database.

Are you editing the wrong table? Maybe editing the emulator table rather than the spell editor table?

Either way this is not a bug or an issue. If you edit data outside the spell editor it won't reflect in the tool.

**Comment by krlsmnk** [comment]
Okay I have the SQL Database open and I'm looking at spell (top heading) -> spell (table)
Values are correct. 
And the DBC file shows the correct values. 
Spell editor doesn't, and if I export the DBC, the exported one has the wrong values. 
I'm not sure how to get it to reimport from the SQL or the DBC (whichever one).
Is spell -> spell the right SQL table? It shows the mechanics and effect points columns.

**Comment by stoneharry** [comment]
I suspect you are using a different database and table to what the spell editor is configured to use. Check your config. It simply is not possible for the export to not export the same values as the configured database.

**Comment by krlsmnk** [comment]
I must have some fundamental misunderstanding how how the SpellEditor works. 
I'm brand new to SQL, so it's probably me doing something dumb. 

I have the (one) SQL server running on my machine. Heidi and SpellEditor both use the same info to "connect" to it. 
Heidi is showing one number, and SpellEditor is showing a different one. 
If I edit a spell in SpellEditor and save the changes, I can close and reopen SpellEditor and the modified values remain. 
Heidi does not show that those values have been (copied? pushed?) into the Database from SpellEditor. 

In the reverse, if I edit something in Heidi, then close and reopen Heidi, those modified values remain in Heidi. 
Reopening SpellEditor does not show those changes. 

So... I'm clearly missing something very fundamental. These two tools seem to be modifying different things.
Assuming all I do is change the cast time of a Vanilla spell: what file, specifically, gets changed when I tell SpellEditor to "Save Spell Changes"?

Where does the .DBC file come into all this? How and when does SpellEditor read or write to that file?
Me pointing SpellEditor to its own DBC export directory, instead of the other directory I've been using, magically made it "see" the changes I made with excel. 
As far as I can tell, the DBC file in both directories is the same.

**Comment by stoneharry** [comment]
1) When you first load the program it will ask you to select SQLite or MySQL. If you select MySQL then you input the connection details.
2) The spell list will be empty. Click Import/Export on the top header bar, and import the spell DBCs. This will import the configured DBC folder into the connected database. The config can be seen by pressing the Config button on the top header bar.
3) Once imported you can edit the spells in the spell editor or in the database. It only loads the spell.dbc and spell visual DBCs from SQL, other data is loaded from the local DBC files, but cannot be edited (e.g: duration, range, etc)

If you add new spells in the database then you need to restart the spell editor for it to see them.

When you click "save spell changes" it is only saving the data to the connected database. To get it to export to a DBC you have to use the Import/Export button.

**Comment by krlsmnk** [comment]
That's what I assumed. I figured it out. 

My SQL _SERVER_ is named "Unnamed"

There is a "spell" _Database_ on that server
There is a "spell" _Table_ in that database
^This was the _Table_ Heidi was pointed at

There exists another _Database_ named "unnamed"
There is a "spell" _Table_ in that database
^This was the _Table_ I didn't realize SpellEditor was pointed at. 

Classic programmer move: name your files w/e because *obviously* it makes sense. 
Not my fault; and not yours either. 
Someone from either the repack or TrinityCore just thought this was a good idea.
