### ISSUE TITLE
I cant seem to get this to work with vmangos?

### ISSUE THREAD

**Issue by patrikpatrik** [stoneharry/WoW-Spell-Editor#191]
Is there some trick or is it a completely different database structure vmangos is using? Thx in advance!

**Comment by stoneharry** [comment]
It's a different structure, the spell editor is only compatible with the DBC structure which no emulator matches exactly.

**Comment by stoneharry** [comment]
See #91 for how to convert from the DBC database into vmangos structure. The query may be out of date but it gives you an idea.

Currently the spell editor has no emulator support because every emulator does things a bit differently and none of them match the DBC structure. It would definitely be a nice feature to integrate with the emulators but it's also a ton of work to support each one.

Closing this issue as answered - feel free to reopen it or open a new issue if you have further questions.

**Comment by patrikpatrik** [comment]
@stoneharry, Ok thank you harry!
