### ISSUE TITLE
Do u have any more info on this Harry?

### ISSUE THREAD

**Issue by Sulan2** [stoneharry/WoW-Spell-Editor#193]
Hey harry, I spent some time trying to figure out what causes Ice Lance to deal triple damage on frozen targets.

Well it turns out that its linked to the Icon it uses and I never thought that the Icon would actualy have a real effect other than the visual look it have as an icon.

Do u have any more info on effects that icons causes?

**Comment by stoneharry** [comment]
There's a ton of spell interactions hardcoded in the emulator based on the family flags, class masks, or spell icon, among other things.

For some silly reason a lot of emulator developers believe that the best way to identify spells is by the icon. Yes, you heard me right -- they code special logic that happens when the icon is a certain ID.

This sounds mental from a modders perspective, but if your only goal is Blizzlike then it's an easy way to capture say 10-20 spells in a single ID check. Unfortunately a lot of emu devs are not supportive of modding. It wans't long ago thatI was arguing in a TrinityCore pull request that in fact a icon ID check is not the best way to implement something like this, especially for new code: https://github.com/TrinityCore/TrinityCore/pull/26859
