### ISSUE TITLE
After importing DBCs, everything comes up as 'Unknown String'

### ISSUE THREAD

**Issue by Madcat124** [stoneharry/WoW-Spell-Editor#245]
![1](https://github.com/user-attachments/assets/40aadd7d-e412-44c9-8ca1-60f52b86df0d)

Hi, 

After importing my DBCs into the spell editor, everything reads as "Unknown String". It looks like all the Spell IDs and effects are fine, at least at a first glance.

How can I fix this?

EDIT: I'm using the Individual Progression Module for Azerothcore which has a Spell.DBC override/patch. I'm not sure if that may have anything to do with it.

**Comment by stoneharry** [comment]
The structure of the DBC file is that each record has a fixed size. Strings a dynamicly sized based on the length of the text, so it basically writes a offset (pointer) into a string block at the end of the file. It reads from the offset until a string terminator character is found.

In this case, all of your string offsets cannot be found in the string block. This is usually due to DBC corruption.

Is your DBC file Blizzlike? Spell editor is not directly compatible with any emulator, it uses the Blizzlike files.

**Comment by Madcat124** [comment]
Thanks for the response. 

Yeah, I downloaded a fresh/updated Spell.dbc and used that. It works fine now. 

Not exactly sure what is different, but the Spell.dbc I was using had different column names/order, I think that may have been the issue.
